import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { type FC, type ReactNode } from 'react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface LayoutProps {
  children: ReactNode

}

export const RootLayout: FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="es">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
