import Skeleton from '@/components/ui/Skeleton'
import { Table, TableBody, TableCell, TableContainer, TableHead, TableHeadCell, TableRow } from '@/components/ui/Table'
import Typography from '@/components/ui/Typography'
import { type FC } from 'react'

const Home: FC = () => {
  return (
    <>
      <Typography variant="h1" align="center" >EntGamers Next Template</Typography>
      <Skeleton />
      <TableContainer
      >
        <Table
        >
          <TableHead>
            <TableRow>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
              <TableHeadCell>Header</TableHeadCell>
            </TableRow>
          </TableHead>
          <TableBody>
            <TableRow>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
              <TableCell>Cell</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </TableContainer>
    </>
  )
}

export default Home
